---
services:
  socialapp:
    image: socialapp:latest
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    # command: gunicorn app.wsgi:application --bind 0.0.0.0:8000 --workers 4 --timeout 120 --log-level debug
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./mediafiles:/app/mediafiles        

  postgres:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django

  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - socialapp
    volumes:
      - ./app/Caddyfile:/etc/caddy/Caddyfile

volumes:
  postgres_data:
  mediafiles: